package com.ogya.dms.common.structures;

public enum ContentType {

	MESSAGE, BCON, REQ_STRT, IP, ADD_IP, REMOVE_IP, PROGRESS, CANCEL, UUID_DISCONNECTED, CLAIM_MESSAGE_STATUS,
	FEED_MESSAGE_STATUS, FEED_GROUP_MESSAGE_STATUS, CLAIM_STATUS_REPORT, FEED_STATUS_REPORT, TRANSIENT

}
