package com.ogya.dms.common.structures;

public enum ContentType {

	MESSAGE, BCON, REQ_BCON, PROGRESS, CANCEL, UUID_DISCONNECTED, CLAIM_MESSAGE_STATUS, FRESH, SENT, RECEIVED, READ,
	CLAIM_STATUS_REPORT, FEED_STATUS_REPORT, TRANSIENT

}
